### PR TITLE
V1.3 fix clear not update

### PR DESCRIPTION
**Pull request by Lingy12**
Please do not merge yet, but please help me check whether the design decision is acceptable or not. The part related to update journal given an addressbook

### CODE REVIEW

**Comment by Lingy12** [comment]
Updated. If you think this it's ok to have an update for journal according to addressbook, then it should be able to work.

**Review by zhXchD — CHANGES_REQUESTED** [review]
It seems better not to refer to `AddressBook` in `Journal`.
Maybe you can implement a method to directly delete all contacts in all journal entries, instead of updating contacts from a given `AddressBook`.

**Comment by Lingy12** [comment]
Updated.

**Review by zhXchD — APPROVED** [review]
LGTM.

**Pull request merged**
